name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
            - název: První interakce
  použití: actions/first-interaction@v1.3.0
  s:
    # Token pro úložiště. Lze předat pomocí {{ secrets.GITHUB_TOKEN }}
    repo-token:
    # Komentář pro příspěvek k prvnímu vydání jednotlivce
    issue-Message: # volitelné
    # Komentář ke zveřejnění prvního požadavku jednotlivce
    pr-message: # volitelné
          
